#!/bin/bash
cd mapColoringUSStates
echo ---- example of a full application using qbsolv
echo -----
./demoStates.sh
echo ---- open in a browser the .svg files to see a colored map
echo ----
cd ..
echo --- using the python interface to qbsolv example
echo ---
python tryDwaveQbsolv.py
./factoring.bash

